- id: 200
  key: satoshi
  currency: btc
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 400
  key: bank
  currency: usd
  sort_order: 2
  bank_accounts:
    -
      bank: 'Bank O Chan'
      branch: 'Super Secure Branch'
      holder: 'Benedict Chan'
      account: '111-222-3333'
